# roles/example/tasks/debian.yml
- name: Install vsftpd server for Debian
  ansible.builtin.apt:
    name: "vsftpd"
    state: present

- name: Update VSFTPD configuration for Debian
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
  notify: restart vsftpd

- name: Update VSFTPD user list for Debian
  ansible.builtin.template:
    src: user_list.j2
    dest: /etc/vsftpd.user_list
  notify: restart vsftpd

- name: Update PAM configuration for Debian
  ansible.builtin.copy:
    src: vsftpd.debian.pam
    dest: /etc/pam.d/vsftpd_nopam
  notify: restart vsftpd